name: Build and Test

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        if: runner.os != 'Windows'

      - name: Grant execute permission for gradlew (Windows)
        run: git update-index --chmod=+x gradlew
        if: runner.os == 'Windows'

      - name: Build and test with Gradle
        run: ./gradlew build test --no-daemon
        shell: bash

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports-${{ matrix.os }}
          path: '**/build/reports/tests/'
